include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "mirdorph.flatpak"

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    before_script:
        - "flatpak install --user -y --noninteractive flathub-beta org.freedesktop.Sdk//21.08beta"
        - "git clone https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable.git && cd org.freedesktop.Sdk.Extension.rust-stable"
        - "git config user.name ci"
        - "git config user.email ci"
        - "git am ../patches/org.freedesktop.Sdk.Extension.rust-stable/0001-update-to-21.08-beta.patch"
        - "flatpak-builder --disable-rofiles-fuse --user --install build-dir org.freedesktop.Sdk.Extension.rust-stable.json"
        - "flatpak remove -y --noninteractive org.freedesktop.Sdk//21.08beta && cd .."
    variables:
        MANIFEST_PATH: "org.gnome.gitlab.ranchester.Mirdorph.json"
        FLATPAK_MODULE: "mirdorph"
        RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
        APP_ID: "org.gnome.gitlab.ranchester.Mirdorph"
    extends: .flatpak

flatpak-test:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    before_script:
        - "flatpak install --user -y --noninteractive flathub-beta org.freedesktop.Sdk//21.08beta"
        - "git clone https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable.git && cd org.freedesktop.Sdk.Extension.rust-stable"
        - "git config user.name ci"
        - "git config user.email ci"
        - "git am ../patches/org.freedesktop.Sdk.Extension.rust-stable/0001-update-to-21.08-beta.patch"
        - "flatpak-builder --disable-rofiles-fuse --user --install build-dir org.freedesktop.Sdk.Extension.rust-stable.json"
        - "flatpak remove -y --noninteractive org.freedesktop.Sdk//21.08beta && cd .."
    script:
      - !reference [.flatpak, script]
      - 'flatpak install -y --noninteractive --user --no-pull --no-related mirdorph.flatpak'
      - 'flatpak run --command="python3" --cwd=$(pwd)/tests --filesystem=$(pwd) org.gnome.gitlab.ranchester.Mirdorph -m pytest -v --junitxml=../report.xml'
    variables:
        MANIFEST_PATH: "org.gnome.gitlab.ranchester.Mirdorph.json"
        FLATPAK_MODULE: "mirdorph"
        RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
        APP_ID: "org.gnome.gitlab.ranchester.Mirdorph"
    extends: .flatpak
    artifacts:
      when: always
      reports:
        junit: report.xml

